// <auto-generated />
namespace HOCAF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Cambios2FichaProgramas : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Cambios2FichaProgramas));
        
        string IMigrationMetadata.Id
        {
            get { return "201803182109311_Cambios2Ficha%Programas"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
